const styles = {
  /* shared */
  body: {
    margin: 0,
    fontFamily: "Arial, sans-serif",
    backgroundColor: "#043927",
    minHeight: "100vh",
    position: "relative",
  },
  watermark: {
    content: '""',
    position: "fixed",
    inset: 0,
    backgroundImage:
      'url("https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/California_State_University%2C_Sacramento_seal.svg/1280px-California_State_University%2C_Sacramento_seal.svg.png")',
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundSize: "500px",
    opacity: 0.08,
    zIndex: 0,
    pointerEvents: "none",
  },
  page: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
  },
  header: {
    backgroundColor: "white",
    padding: "20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "18px",
    fontWeight: "bold",
    borderBottom: "2px solid #ccc",
  },
  headerTitle: {
    cursor: "pointer",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    fontWeight: "normal",
    fontSize: "16px",
  },
  nav: {
    display: "flex",
    gap: "25px",
  },
  searchIcon: {
    fontSize: "20px",
    cursor: "pointer",
  },
  bell: {
    fontSize: "22px",
    cursor: "pointer",
  },
  loginBox: {
    backgroundColor: "yellow",
    padding: "6px 12px",
    borderRadius: "12px",
    fontSize: "14px",
    fontWeight: "bold",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },

  /* home page */
  main: {
    position: "relative",
    display: "flex",
    justifyContent: "space-between",
    flex: 1,
  },
  leftBoxes: {
    width: "260px",
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    padding: "20px",
  },
  box: {
    width: "220px",
    height: "100px",
    backgroundColor: "white",
    borderRadius: "10px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    padding: "10px",
  },
  boxContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "5px",
  },
  boxTitle: {
    fontWeight: "bold",
    fontSize: "16px",
  },
  date: {
    fontWeight: "bold",
    fontSize: "14px",
  },
  eventTitle: {
    fontSize: "14px",
  },
  eventTime: {
    fontSize: "13px",
    opacity: 0.7,
  },
  rightImage: {
    width: "300px",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  img: {
    width: "100%",
    borderRadius: "12px",
  },
  topText: {
    position: "absolute",
    top: "20px",
    left: "50%",
    transform: "translateX(-50%)",
    textAlign: "center",
  },
  welcome: {
    fontSize: "22px",
    fontWeight: "bold",
    marginBottom: "5px",
    color: "#FFC107",
  },
  subtext: {
    fontSize: "16px",
    color: "#FFC107",
    opacity: 0.8,
  },
  content: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    textAlign: "center",
  },
  centerContainer: {
    color: "gray",
  },
  smallTitle: {
    fontSize: "2.5rem",
    marginBottom: "10px",
  },
  bigTitle: {
    fontSize: "7rem",
    fontWeight: "bold",
    lineHeight: 1,
  },

  /* login page */
  loginBody: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "40px 20px",
  },
  loginContainer: {
    backgroundColor: "white",
    padding: "40px 35px",
    borderRadius: "12px",
    width: "400px",
    boxShadow: "0 8px 24px rgba(0,0,0,0.3)",
    fontFamily: "'Poppins', Arial, sans-serif",
    animation: "fadeIn 0.4s ease",
  },
  logoSection: {
    textAlign: "center",
    marginBottom: "28px",
  },
  sacLogo: {
    width: "60px",
    height: "60px",
    backgroundColor: "#043927",
    borderRadius: "50%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    margin: "0 auto 12px auto",
  },
  sacLogoSpan: {
    color: "#C4B000",
    fontSize: "28px",
    fontWeight: 700,
  },
  logoH1: {
    fontSize: "22px",
    color: "#043927",
    fontWeight: 700,
  },
  logoP: {
    fontSize: "13px",
    color: "#666",
    marginTop: "4px",
  },
  formGroup: {
    marginBottom: "18px",
  },
  label: {
    display: "block",
    fontSize: "13px",
    fontWeight: 500,
    color: "#333",
    marginBottom: "6px",
  },
  input: {
    width: "100%",
    padding: "11px 14px",
    border: "1.5px solid #ddd",
    borderRadius: "8px",
    fontSize: "14px",
    fontFamily: "'Poppins', Arial, sans-serif",
    color: "#333",
    outline: "none",
    boxSizing: "border-box",
  },
  inputError: {
    borderColor: "#e53e3e",
  },
  errorText: {
    color: "#e53e3e",
    fontSize: "12px",
    marginTop: "4px",
  },
  passwordWrapper: {
    position: "relative",
  },
  togglePassword: {
    position: "absolute",
    right: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "13px",
    color: "#888",
    padding: 0,
    fontFamily: "'Poppins', Arial, sans-serif",
  },
  formOptions: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "22px",
    fontSize: "13px",
  },
  rememberMe: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#555",
  },
  forgotLink: {
    color: "#043927",
    textDecoration: "none",
    fontWeight: 500,
    cursor: "pointer",
  },
  loginBtn: {
    width: "100%",
    padding: "12px",
    backgroundColor: "#043927",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "15px",
    fontWeight: 600,
    fontFamily: "'Poppins', Arial, sans-serif",
    cursor: "pointer",
  },
  divider: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    margin: "20px 0",
    color: "#aaa",
    fontSize: "13px",
  },
  dividerLine: {
    flex: 1,
    height: "1px",
    backgroundColor: "#e5e5e5",
  },
  signupText: {
    textAlign: "center",
    fontSize: "13px",
    color: "#666",
  },
  signupLink: {
    color: "#C4B000",
    fontWeight: 600,
    textDecoration: "none",
    cursor: "pointer",
  },
  backLink: {
    textAlign: "center",
    fontSize: "13px",
    color: "#888",
    marginTop: "14px",
  },
  backLinkA: {
    color: "#043927",
    textDecoration: "none",
    fontWeight: 500,
    cursor: "pointer",
  },
  successMsg: {
    backgroundColor: "#d4edda",
    color: "#155724",
    border: "1px solid #c3e6cb",
    padding: "10px 14px",
    borderRadius: "8px",
    fontSize: "13px",
    textAlign: "center",
    marginTop: "16px",
  },
};

export default styles;
